// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.2
// source: internal/gossip/g.proto

package gossip_grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NodeState int32

const (
	NodeState_NODE_STATE_ALIVE   NodeState = 0
	NodeState_NODE_STATE_SUSPECT NodeState = 1
	NodeState_NODE_STATE_DEAD    NodeState = 2
)

// Enum value maps for NodeState.
var (
	NodeState_name = map[int32]string{
		0: "NODE_STATE_ALIVE",
		1: "NODE_STATE_SUSPECT",
		2: "NODE_STATE_DEAD",
	}
	NodeState_value = map[string]int32{
		"NODE_STATE_ALIVE":   0,
		"NODE_STATE_SUSPECT": 1,
		"NODE_STATE_DEAD":    2,
	}
)

func (x NodeState) Enum() *NodeState {
	p := new(NodeState)
	*p = x
	return p
}

func (x NodeState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeState) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_gossip_g_proto_enumTypes[0].Descriptor()
}

func (NodeState) Type() protoreflect.EnumType {
	return &file_internal_gossip_g_proto_enumTypes[0]
}

func (x NodeState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeState.Descriptor instead.
func (NodeState) EnumDescriptor() ([]byte, []int) {
	return file_internal_gossip_g_proto_rawDescGZIP(), []int{0}
}

type Digest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Incarnation   uint64                 `protobuf:"varint,2,opt,name=incarnation,proto3" json:"incarnation,omitempty"`
	State         NodeState              `protobuf:"varint,3,opt,name=state,proto3,enum=gossip.v1.NodeState" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Digest) Reset() {
	*x = Digest{}
	mi := &file_internal_gossip_g_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Digest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Digest) ProtoMessage() {}

func (x *Digest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_gossip_g_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Digest.ProtoReflect.Descriptor instead.
func (*Digest) Descriptor() ([]byte, []int) {
	return file_internal_gossip_g_proto_rawDescGZIP(), []int{0}
}

func (x *Digest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Digest) GetIncarnation() uint64 {
	if x != nil {
		return x.Incarnation
	}
	return 0
}

func (x *Digest) GetState() NodeState {
	if x != nil {
		return x.State
	}
	return NodeState_NODE_STATE_ALIVE
}

type Member struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	GossipGrpcAddress string                 `protobuf:"bytes,2,opt,name=gossip_grpc_address,json=gossipGrpcAddress,proto3" json:"gossip_grpc_address,omitempty"`
	ClientAddress     string                 `protobuf:"bytes,3,opt,name=client_address,json=clientAddress,proto3" json:"client_address,omitempty"`
	Weight            int32                  `protobuf:"varint,4,opt,name=weight,proto3" json:"weight,omitempty"`
	State             NodeState              `protobuf:"varint,5,opt,name=state,proto3,enum=gossip.v1.NodeState" json:"state,omitempty"`
	Incarnation       uint64                 `protobuf:"varint,6,opt,name=incarnation,proto3" json:"incarnation,omitempty"`
	StateUpdated      int64                  `protobuf:"varint,7,opt,name=state_updated,json=stateUpdated,proto3" json:"state_updated,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Member) Reset() {
	*x = Member{}
	mi := &file_internal_gossip_g_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Member) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Member) ProtoMessage() {}

func (x *Member) ProtoReflect() protoreflect.Message {
	mi := &file_internal_gossip_g_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Member.ProtoReflect.Descriptor instead.
func (*Member) Descriptor() ([]byte, []int) {
	return file_internal_gossip_g_proto_rawDescGZIP(), []int{1}
}

func (x *Member) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Member) GetGossipGrpcAddress() string {
	if x != nil {
		return x.GossipGrpcAddress
	}
	return ""
}

func (x *Member) GetClientAddress() string {
	if x != nil {
		return x.ClientAddress
	}
	return ""
}

func (x *Member) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *Member) GetState() NodeState {
	if x != nil {
		return x.State
	}
	return NodeState_NODE_STATE_ALIVE
}

func (x *Member) GetIncarnation() uint64 {
	if x != nil {
		return x.Incarnation
	}
	return 0
}

func (x *Member) GetStateUpdated() int64 {
	if x != nil {
		return x.StateUpdated
	}
	return 0
}

type PingRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	FromId          string                 `protobuf:"bytes,1,opt,name=from_id,json=fromId,proto3" json:"from_id,omitempty"`
	FromIncarnation uint64                 `protobuf:"varint,2,opt,name=from_incarnation,json=fromIncarnation,proto3" json:"from_incarnation,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_internal_gossip_g_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_gossip_g_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_internal_gossip_g_proto_rawDescGZIP(), []int{2}
}

func (x *PingRequest) GetFromId() string {
	if x != nil {
		return x.FromId
	}
	return ""
}

func (x *PingRequest) GetFromIncarnation() uint64 {
	if x != nil {
		return x.FromIncarnation
	}
	return 0
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_internal_gossip_g_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_gossip_g_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_internal_gossip_g_proto_rawDescGZIP(), []int{3}
}

func (x *PingResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type PushPullRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromId        string                 `protobuf:"bytes,1,opt,name=from_id,json=fromId,proto3" json:"from_id,omitempty"`
	Digests       []*Digest              `protobuf:"bytes,2,rep,name=digests,proto3" json:"digests,omitempty"`
	FullMembers   []*Member              `protobuf:"bytes,3,rep,name=full_members,json=fullMembers,proto3" json:"full_members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushPullRequest) Reset() {
	*x = PushPullRequest{}
	mi := &file_internal_gossip_g_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushPullRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushPullRequest) ProtoMessage() {}

func (x *PushPullRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_gossip_g_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushPullRequest.ProtoReflect.Descriptor instead.
func (*PushPullRequest) Descriptor() ([]byte, []int) {
	return file_internal_gossip_g_proto_rawDescGZIP(), []int{4}
}

func (x *PushPullRequest) GetFromId() string {
	if x != nil {
		return x.FromId
	}
	return ""
}

func (x *PushPullRequest) GetDigests() []*Digest {
	if x != nil {
		return x.Digests
	}
	return nil
}

func (x *PushPullRequest) GetFullMembers() []*Member {
	if x != nil {
		return x.FullMembers
	}
	return nil
}

type PushPullResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Delta         []*Member              `protobuf:"bytes,1,rep,name=delta,proto3" json:"delta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushPullResponse) Reset() {
	*x = PushPullResponse{}
	mi := &file_internal_gossip_g_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushPullResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushPullResponse) ProtoMessage() {}

func (x *PushPullResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_gossip_g_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushPullResponse.ProtoReflect.Descriptor instead.
func (*PushPullResponse) Descriptor() ([]byte, []int) {
	return file_internal_gossip_g_proto_rawDescGZIP(), []int{5}
}

func (x *PushPullResponse) GetDelta() []*Member {
	if x != nil {
		return x.Delta
	}
	return nil
}

var File_internal_gossip_g_proto protoreflect.FileDescriptor

const file_internal_gossip_g_proto_rawDesc = "" +
	"\n" +
	"\x17internal/gossip/g.proto\x12\tgossip.v1\"f\n" +
	"\x06Digest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12 \n" +
	"\vincarnation\x18\x02 \x01(\x04R\vincarnation\x12*\n" +
	"\x05state\x18\x03 \x01(\x0e2\x14.gossip.v1.NodeStateR\x05state\"\xfa\x01\n" +
	"\x06Member\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12.\n" +
	"\x13gossip_grpc_address\x18\x02 \x01(\tR\x11gossipGrpcAddress\x12%\n" +
	"\x0eclient_address\x18\x03 \x01(\tR\rclientAddress\x12\x16\n" +
	"\x06weight\x18\x04 \x01(\x05R\x06weight\x12*\n" +
	"\x05state\x18\x05 \x01(\x0e2\x14.gossip.v1.NodeStateR\x05state\x12 \n" +
	"\vincarnation\x18\x06 \x01(\x04R\vincarnation\x12#\n" +
	"\rstate_updated\x18\a \x01(\x03R\fstateUpdated\"Q\n" +
	"\vPingRequest\x12\x17\n" +
	"\afrom_id\x18\x01 \x01(\tR\x06fromId\x12)\n" +
	"\x10from_incarnation\x18\x02 \x01(\x04R\x0ffromIncarnation\"\x1e\n" +
	"\fPingResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"\x8d\x01\n" +
	"\x0fPushPullRequest\x12\x17\n" +
	"\afrom_id\x18\x01 \x01(\tR\x06fromId\x12+\n" +
	"\adigests\x18\x02 \x03(\v2\x11.gossip.v1.DigestR\adigests\x124\n" +
	"\ffull_members\x18\x03 \x03(\v2\x11.gossip.v1.MemberR\vfullMembers\";\n" +
	"\x10PushPullResponse\x12'\n" +
	"\x05delta\x18\x01 \x03(\v2\x11.gossip.v1.MemberR\x05delta*N\n" +
	"\tNodeState\x12\x14\n" +
	"\x10NODE_STATE_ALIVE\x10\x00\x12\x16\n" +
	"\x12NODE_STATE_SUSPECT\x10\x01\x12\x13\n" +
	"\x0fNODE_STATE_DEAD\x10\x022\x8d\x01\n" +
	"\rGossipService\x127\n" +
	"\x04Ping\x12\x16.gossip.v1.PingRequest\x1a\x17.gossip.v1.PingResponse\x12C\n" +
	"\bPushPull\x12\x1a.gossip.v1.PushPullRequest\x1a\x1b.gossip.v1.PushPullResponseB+Z)./internal/gossip/gossip_grpc;gossip_grpcb\x06proto3"

var (
	file_internal_gossip_g_proto_rawDescOnce sync.Once
	file_internal_gossip_g_proto_rawDescData []byte
)

func file_internal_gossip_g_proto_rawDescGZIP() []byte {
	file_internal_gossip_g_proto_rawDescOnce.Do(func() {
		file_internal_gossip_g_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_gossip_g_proto_rawDesc), len(file_internal_gossip_g_proto_rawDesc)))
	})
	return file_internal_gossip_g_proto_rawDescData
}

var file_internal_gossip_g_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_gossip_g_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_internal_gossip_g_proto_goTypes = []any{
	(NodeState)(0),           // 0: gossip.v1.NodeState
	(*Digest)(nil),           // 1: gossip.v1.Digest
	(*Member)(nil),           // 2: gossip.v1.Member
	(*PingRequest)(nil),      // 3: gossip.v1.PingRequest
	(*PingResponse)(nil),     // 4: gossip.v1.PingResponse
	(*PushPullRequest)(nil),  // 5: gossip.v1.PushPullRequest
	(*PushPullResponse)(nil), // 6: gossip.v1.PushPullResponse
}
var file_internal_gossip_g_proto_depIdxs = []int32{
	0, // 0: gossip.v1.Digest.state:type_name -> gossip.v1.NodeState
	0, // 1: gossip.v1.Member.state:type_name -> gossip.v1.NodeState
	1, // 2: gossip.v1.PushPullRequest.digests:type_name -> gossip.v1.Digest
	2, // 3: gossip.v1.PushPullRequest.full_members:type_name -> gossip.v1.Member
	2, // 4: gossip.v1.PushPullResponse.delta:type_name -> gossip.v1.Member
	3, // 5: gossip.v1.GossipService.Ping:input_type -> gossip.v1.PingRequest
	5, // 6: gossip.v1.GossipService.PushPull:input_type -> gossip.v1.PushPullRequest
	4, // 7: gossip.v1.GossipService.Ping:output_type -> gossip.v1.PingResponse
	6, // 8: gossip.v1.GossipService.PushPull:output_type -> gossip.v1.PushPullResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_internal_gossip_g_proto_init() }
func file_internal_gossip_g_proto_init() {
	if File_internal_gossip_g_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_gossip_g_proto_rawDesc), len(file_internal_gossip_g_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_gossip_g_proto_goTypes,
		DependencyIndexes: file_internal_gossip_g_proto_depIdxs,
		EnumInfos:         file_internal_gossip_g_proto_enumTypes,
		MessageInfos:      file_internal_gossip_g_proto_msgTypes,
	}.Build()
	File_internal_gossip_g_proto = out.File
	file_internal_gossip_g_proto_goTypes = nil
	file_internal_gossip_g_proto_depIdxs = nil
}
