// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.2
// source: internal/chash/c.proto

package chash_grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 命令操作枚举
type CommandOperation int32

const (
	CommandOperation_OP_PUT    CommandOperation = 0
	CommandOperation_OP_DELETE CommandOperation = 1
)

// Enum value maps for CommandOperation.
var (
	CommandOperation_name = map[int32]string{
		0: "OP_PUT",
		1: "OP_DELETE",
	}
	CommandOperation_value = map[string]int32{
		"OP_PUT":    0,
		"OP_DELETE": 1,
	}
)

func (x CommandOperation) Enum() *CommandOperation {
	p := new(CommandOperation)
	*p = x
	return p
}

func (x CommandOperation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandOperation) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_chash_c_proto_enumTypes[0].Descriptor()
}

func (CommandOperation) Type() protoreflect.EnumType {
	return &file_internal_chash_c_proto_enumTypes[0]
}

func (x CommandOperation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandOperation.Descriptor instead.
func (CommandOperation) EnumDescriptor() ([]byte, []int) {
	return file_internal_chash_c_proto_rawDescGZIP(), []int{0}
}

// 迁移状态枚举
type MigrationStatus int32

const (
	MigrationStatus_STATUS_PENDING    MigrationStatus = 0
	MigrationStatus_STATUS_INPROGRESS MigrationStatus = 1
	MigrationStatus_STATUS_COMPLETED  MigrationStatus = 2
)

// Enum value maps for MigrationStatus.
var (
	MigrationStatus_name = map[int32]string{
		0: "STATUS_PENDING",
		1: "STATUS_INPROGRESS",
		2: "STATUS_COMPLETED",
	}
	MigrationStatus_value = map[string]int32{
		"STATUS_PENDING":    0,
		"STATUS_INPROGRESS": 1,
		"STATUS_COMPLETED":  2,
	}
)

func (x MigrationStatus) Enum() *MigrationStatus {
	p := new(MigrationStatus)
	*p = x
	return p
}

func (x MigrationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MigrationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_chash_c_proto_enumTypes[1].Descriptor()
}

func (MigrationStatus) Type() protoreflect.EnumType {
	return &file_internal_chash_c_proto_enumTypes[1]
}

func (x MigrationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MigrationStatus.Descriptor instead.
func (MigrationStatus) EnumDescriptor() ([]byte, []int) {
	return file_internal_chash_c_proto_rawDescGZIP(), []int{1}
}

// 命令消息
type Command struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Op            CommandOperation       `protobuf:"varint,1,opt,name=op,proto3,enum=chash.v1.CommandOperation" json:"op,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_internal_chash_c_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_internal_chash_c_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_internal_chash_c_proto_rawDescGZIP(), []int{0}
}

func (x *Command) GetOp() CommandOperation {
	if x != nil {
		return x.Op
	}
	return CommandOperation_OP_PUT
}

func (x *Command) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Command) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// 键值对消息
type KVPair struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KVPair) Reset() {
	*x = KVPair{}
	mi := &file_internal_chash_c_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KVPair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KVPair) ProtoMessage() {}

func (x *KVPair) ProtoReflect() protoreflect.Message {
	mi := &file_internal_chash_c_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KVPair.ProtoReflect.Descriptor instead.
func (*KVPair) Descriptor() ([]byte, []int) {
	return file_internal_chash_c_proto_rawDescGZIP(), []int{1}
}

func (x *KVPair) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KVPair) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// 迁移计划集合消息
type MovePlanHint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Epoch         uint64                 `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	StartHash     uint32                 `protobuf:"varint,2,opt,name=start_hash,json=startHash,proto3" json:"start_hash,omitempty"`
	EndHash       uint32                 `protobuf:"varint,3,opt,name=end_hash,json=endHash,proto3" json:"end_hash,omitempty"`
	OldOwners     []string               `protobuf:"bytes,4,rep,name=old_owners,json=oldOwners,proto3" json:"old_owners,omitempty"`
	NewOwners     []string               `protobuf:"bytes,5,rep,name=new_owners,json=newOwners,proto3" json:"new_owners,omitempty"`
	Status        MigrationStatus        `protobuf:"varint,6,opt,name=status,proto3,enum=chash.v1.MigrationStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MovePlanHint) Reset() {
	*x = MovePlanHint{}
	mi := &file_internal_chash_c_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MovePlanHint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovePlanHint) ProtoMessage() {}

func (x *MovePlanHint) ProtoReflect() protoreflect.Message {
	mi := &file_internal_chash_c_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovePlanHint.ProtoReflect.Descriptor instead.
func (*MovePlanHint) Descriptor() ([]byte, []int) {
	return file_internal_chash_c_proto_rawDescGZIP(), []int{2}
}

func (x *MovePlanHint) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *MovePlanHint) GetStartHash() uint32 {
	if x != nil {
		return x.StartHash
	}
	return 0
}

func (x *MovePlanHint) GetEndHash() uint32 {
	if x != nil {
		return x.EndHash
	}
	return 0
}

func (x *MovePlanHint) GetOldOwners() []string {
	if x != nil {
		return x.OldOwners
	}
	return nil
}

func (x *MovePlanHint) GetNewOwners() []string {
	if x != nil {
		return x.NewOwners
	}
	return nil
}

func (x *MovePlanHint) GetStatus() MigrationStatus {
	if x != nil {
		return x.Status
	}
	return MigrationStatus_STATUS_PENDING
}

// 批量推送请求消息
type PushBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MoveId        uint32                 `protobuf:"varint,1,opt,name=move_id,json=moveId,proto3" json:"move_id,omitempty"`
	Kvs           []*KVPair              `protobuf:"bytes,2,rep,name=kvs,proto3" json:"kvs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushBatchRequest) Reset() {
	*x = PushBatchRequest{}
	mi := &file_internal_chash_c_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushBatchRequest) ProtoMessage() {}

func (x *PushBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_chash_c_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushBatchRequest.ProtoReflect.Descriptor instead.
func (*PushBatchRequest) Descriptor() ([]byte, []int) {
	return file_internal_chash_c_proto_rawDescGZIP(), []int{3}
}

func (x *PushBatchRequest) GetMoveId() uint32 {
	if x != nil {
		return x.MoveId
	}
	return 0
}

func (x *PushBatchRequest) GetKvs() []*KVPair {
	if x != nil {
		return x.Kvs
	}
	return nil
}

// 批量推送响应消息
type PushBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushBatchResponse) Reset() {
	*x = PushBatchResponse{}
	mi := &file_internal_chash_c_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushBatchResponse) ProtoMessage() {}

func (x *PushBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_chash_c_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushBatchResponse.ProtoReflect.Descriptor instead.
func (*PushBatchResponse) Descriptor() ([]byte, []int) {
	return file_internal_chash_c_proto_rawDescGZIP(), []int{4}
}

func (x *PushBatchResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

// 范围拉取请求消息
type PullRangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MoveId        uint32                 `protobuf:"varint,1,opt,name=move_id,json=moveId,proto3" json:"move_id,omitempty"`
	StartHash     uint32                 `protobuf:"varint,2,opt,name=start_hash,json=startHash,proto3" json:"start_hash,omitempty"`
	EndHash       uint32                 `protobuf:"varint,3,opt,name=end_hash,json=endHash,proto3" json:"end_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullRangeRequest) Reset() {
	*x = PullRangeRequest{}
	mi := &file_internal_chash_c_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullRangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullRangeRequest) ProtoMessage() {}

func (x *PullRangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_chash_c_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullRangeRequest.ProtoReflect.Descriptor instead.
func (*PullRangeRequest) Descriptor() ([]byte, []int) {
	return file_internal_chash_c_proto_rawDescGZIP(), []int{5}
}

func (x *PullRangeRequest) GetMoveId() uint32 {
	if x != nil {
		return x.MoveId
	}
	return 0
}

func (x *PullRangeRequest) GetStartHash() uint32 {
	if x != nil {
		return x.StartHash
	}
	return 0
}

func (x *PullRangeRequest) GetEndHash() uint32 {
	if x != nil {
		return x.EndHash
	}
	return 0
}

// 范围拉取响应消息
type PullRangeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kvs           []*KVPair              `protobuf:"bytes,1,rep,name=kvs,proto3" json:"kvs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullRangeResponse) Reset() {
	*x = PullRangeResponse{}
	mi := &file_internal_chash_c_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullRangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullRangeResponse) ProtoMessage() {}

func (x *PullRangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_chash_c_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullRangeResponse.ProtoReflect.Descriptor instead.
func (*PullRangeResponse) Descriptor() ([]byte, []int) {
	return file_internal_chash_c_proto_rawDescGZIP(), []int{6}
}

func (x *PullRangeResponse) GetKvs() []*KVPair {
	if x != nil {
		return x.Kvs
	}
	return nil
}

// 数据复制请求消息
type ReplicateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cmds          []*Command             `protobuf:"bytes,1,rep,name=cmds,proto3" json:"cmds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicateRequest) Reset() {
	*x = ReplicateRequest{}
	mi := &file_internal_chash_c_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicateRequest) ProtoMessage() {}

func (x *ReplicateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_chash_c_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicateRequest.ProtoReflect.Descriptor instead.
func (*ReplicateRequest) Descriptor() ([]byte, []int) {
	return file_internal_chash_c_proto_rawDescGZIP(), []int{7}
}

func (x *ReplicateRequest) GetCmds() []*Command {
	if x != nil {
		return x.Cmds
	}
	return nil
}

// 数据复制响应消息
type ReplicateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicateResponse) Reset() {
	*x = ReplicateResponse{}
	mi := &file_internal_chash_c_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicateResponse) ProtoMessage() {}

func (x *ReplicateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_chash_c_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicateResponse.ProtoReflect.Descriptor instead.
func (*ReplicateResponse) Descriptor() ([]byte, []int) {
	return file_internal_chash_c_proto_rawDescGZIP(), []int{8}
}

func (x *ReplicateResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

// 迁移计划预告消息
type AnnouncePlanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plans         []*MovePlanHint        `protobuf:"bytes,1,rep,name=plans,proto3" json:"plans,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnnouncePlanRequest) Reset() {
	*x = AnnouncePlanRequest{}
	mi := &file_internal_chash_c_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnnouncePlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnnouncePlanRequest) ProtoMessage() {}

func (x *AnnouncePlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_chash_c_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnnouncePlanRequest.ProtoReflect.Descriptor instead.
func (*AnnouncePlanRequest) Descriptor() ([]byte, []int) {
	return file_internal_chash_c_proto_rawDescGZIP(), []int{9}
}

func (x *AnnouncePlanRequest) GetPlans() []*MovePlanHint {
	if x != nil {
		return x.Plans
	}
	return nil
}

// 迁移计划预告响应消息
type AckPlan struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckPlan) Reset() {
	*x = AckPlan{}
	mi := &file_internal_chash_c_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckPlan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckPlan) ProtoMessage() {}

func (x *AckPlan) ProtoReflect() protoreflect.Message {
	mi := &file_internal_chash_c_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckPlan.ProtoReflect.Descriptor instead.
func (*AckPlan) Descriptor() ([]byte, []int) {
	return file_internal_chash_c_proto_rawDescGZIP(), []int{10}
}

func (x *AckPlan) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

// 拉取迁移计划请求消息
type PullPlanSinceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SinceEpoch    uint64                 `protobuf:"varint,1,opt,name=since_epoch,json=sinceEpoch,proto3" json:"since_epoch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullPlanSinceRequest) Reset() {
	*x = PullPlanSinceRequest{}
	mi := &file_internal_chash_c_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullPlanSinceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullPlanSinceRequest) ProtoMessage() {}

func (x *PullPlanSinceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_chash_c_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullPlanSinceRequest.ProtoReflect.Descriptor instead.
func (*PullPlanSinceRequest) Descriptor() ([]byte, []int) {
	return file_internal_chash_c_proto_rawDescGZIP(), []int{11}
}

func (x *PullPlanSinceRequest) GetSinceEpoch() uint64 {
	if x != nil {
		return x.SinceEpoch
	}
	return 0
}

// 拉取迁移计划响应消息
type PullPlanSinceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plans         []*MovePlanHint        `protobuf:"bytes,1,rep,name=plans,proto3" json:"plans,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullPlanSinceResponse) Reset() {
	*x = PullPlanSinceResponse{}
	mi := &file_internal_chash_c_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullPlanSinceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullPlanSinceResponse) ProtoMessage() {}

func (x *PullPlanSinceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_chash_c_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullPlanSinceResponse.ProtoReflect.Descriptor instead.
func (*PullPlanSinceResponse) Descriptor() ([]byte, []int) {
	return file_internal_chash_c_proto_rawDescGZIP(), []int{12}
}

func (x *PullPlanSinceResponse) GetPlans() []*MovePlanHint {
	if x != nil {
		return x.Plans
	}
	return nil
}

var File_internal_chash_c_proto protoreflect.FileDescriptor

const file_internal_chash_c_proto_rawDesc = "" +
	"\n" +
	"\x16internal/chash/c.proto\x12\bchash.v1\"]\n" +
	"\aCommand\x12*\n" +
	"\x02op\x18\x01 \x01(\x0e2\x1a.chash.v1.CommandOperationR\x02op\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\"0\n" +
	"\x06KVPair\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\xcf\x01\n" +
	"\fMovePlanHint\x12\x14\n" +
	"\x05epoch\x18\x01 \x01(\x04R\x05epoch\x12\x1d\n" +
	"\n" +
	"start_hash\x18\x02 \x01(\rR\tstartHash\x12\x19\n" +
	"\bend_hash\x18\x03 \x01(\rR\aendHash\x12\x1d\n" +
	"\n" +
	"old_owners\x18\x04 \x03(\tR\toldOwners\x12\x1d\n" +
	"\n" +
	"new_owners\x18\x05 \x03(\tR\tnewOwners\x121\n" +
	"\x06status\x18\x06 \x01(\x0e2\x19.chash.v1.MigrationStatusR\x06status\"O\n" +
	"\x10PushBatchRequest\x12\x17\n" +
	"\amove_id\x18\x01 \x01(\rR\x06moveId\x12\"\n" +
	"\x03kvs\x18\x02 \x03(\v2\x10.chash.v1.KVPairR\x03kvs\"#\n" +
	"\x11PushBatchResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"e\n" +
	"\x10PullRangeRequest\x12\x17\n" +
	"\amove_id\x18\x01 \x01(\rR\x06moveId\x12\x1d\n" +
	"\n" +
	"start_hash\x18\x02 \x01(\rR\tstartHash\x12\x19\n" +
	"\bend_hash\x18\x03 \x01(\rR\aendHash\"7\n" +
	"\x11PullRangeResponse\x12\"\n" +
	"\x03kvs\x18\x01 \x03(\v2\x10.chash.v1.KVPairR\x03kvs\"9\n" +
	"\x10ReplicateRequest\x12%\n" +
	"\x04cmds\x18\x01 \x03(\v2\x11.chash.v1.CommandR\x04cmds\"#\n" +
	"\x11ReplicateResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"C\n" +
	"\x13AnnouncePlanRequest\x12,\n" +
	"\x05plans\x18\x01 \x03(\v2\x16.chash.v1.MovePlanHintR\x05plans\"\x19\n" +
	"\aAckPlan\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"7\n" +
	"\x14PullPlanSinceRequest\x12\x1f\n" +
	"\vsince_epoch\x18\x01 \x01(\x04R\n" +
	"sinceEpoch\"E\n" +
	"\x15PullPlanSinceResponse\x12,\n" +
	"\x05plans\x18\x01 \x03(\v2\x16.chash.v1.MovePlanHintR\x05plans*-\n" +
	"\x10CommandOperation\x12\n" +
	"\n" +
	"\x06OP_PUT\x10\x00\x12\r\n" +
	"\tOP_DELETE\x10\x01*R\n" +
	"\x0fMigrationStatus\x12\x12\n" +
	"\x0eSTATUS_PENDING\x10\x00\x12\x15\n" +
	"\x11STATUS_INPROGRESS\x10\x01\x12\x14\n" +
	"\x10STATUS_COMPLETED\x10\x022\xf4\x02\n" +
	"\fCHashService\x12D\n" +
	"\tPushBatch\x12\x1a.chash.v1.PushBatchRequest\x1a\x1b.chash.v1.PushBatchResponse\x12D\n" +
	"\tPullRange\x12\x1a.chash.v1.PullRangeRequest\x1a\x1b.chash.v1.PullRangeResponse\x12D\n" +
	"\tReplicate\x12\x1a.chash.v1.ReplicateRequest\x1a\x1b.chash.v1.ReplicateResponse\x12@\n" +
	"\fAnnouncePlan\x12\x1d.chash.v1.AnnouncePlanRequest\x1a\x11.chash.v1.AckPlan\x12P\n" +
	"\rPullPlanSince\x12\x1e.chash.v1.PullPlanSinceRequest\x1a\x1f.chash.v1.PullPlanSinceResponseB(Z&./internal/chash/chash_grpc;chash_grpcb\x06proto3"

var (
	file_internal_chash_c_proto_rawDescOnce sync.Once
	file_internal_chash_c_proto_rawDescData []byte
)

func file_internal_chash_c_proto_rawDescGZIP() []byte {
	file_internal_chash_c_proto_rawDescOnce.Do(func() {
		file_internal_chash_c_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_chash_c_proto_rawDesc), len(file_internal_chash_c_proto_rawDesc)))
	})
	return file_internal_chash_c_proto_rawDescData
}

var file_internal_chash_c_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_internal_chash_c_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_internal_chash_c_proto_goTypes = []any{
	(CommandOperation)(0),         // 0: chash.v1.CommandOperation
	(MigrationStatus)(0),          // 1: chash.v1.MigrationStatus
	(*Command)(nil),               // 2: chash.v1.Command
	(*KVPair)(nil),                // 3: chash.v1.KVPair
	(*MovePlanHint)(nil),          // 4: chash.v1.MovePlanHint
	(*PushBatchRequest)(nil),      // 5: chash.v1.PushBatchRequest
	(*PushBatchResponse)(nil),     // 6: chash.v1.PushBatchResponse
	(*PullRangeRequest)(nil),      // 7: chash.v1.PullRangeRequest
	(*PullRangeResponse)(nil),     // 8: chash.v1.PullRangeResponse
	(*ReplicateRequest)(nil),      // 9: chash.v1.ReplicateRequest
	(*ReplicateResponse)(nil),     // 10: chash.v1.ReplicateResponse
	(*AnnouncePlanRequest)(nil),   // 11: chash.v1.AnnouncePlanRequest
	(*AckPlan)(nil),               // 12: chash.v1.AckPlan
	(*PullPlanSinceRequest)(nil),  // 13: chash.v1.PullPlanSinceRequest
	(*PullPlanSinceResponse)(nil), // 14: chash.v1.PullPlanSinceResponse
}
var file_internal_chash_c_proto_depIdxs = []int32{
	0,  // 0: chash.v1.Command.op:type_name -> chash.v1.CommandOperation
	1,  // 1: chash.v1.MovePlanHint.status:type_name -> chash.v1.MigrationStatus
	3,  // 2: chash.v1.PushBatchRequest.kvs:type_name -> chash.v1.KVPair
	3,  // 3: chash.v1.PullRangeResponse.kvs:type_name -> chash.v1.KVPair
	2,  // 4: chash.v1.ReplicateRequest.cmds:type_name -> chash.v1.Command
	4,  // 5: chash.v1.AnnouncePlanRequest.plans:type_name -> chash.v1.MovePlanHint
	4,  // 6: chash.v1.PullPlanSinceResponse.plans:type_name -> chash.v1.MovePlanHint
	5,  // 7: chash.v1.CHashService.PushBatch:input_type -> chash.v1.PushBatchRequest
	7,  // 8: chash.v1.CHashService.PullRange:input_type -> chash.v1.PullRangeRequest
	9,  // 9: chash.v1.CHashService.Replicate:input_type -> chash.v1.ReplicateRequest
	11, // 10: chash.v1.CHashService.AnnouncePlan:input_type -> chash.v1.AnnouncePlanRequest
	13, // 11: chash.v1.CHashService.PullPlanSince:input_type -> chash.v1.PullPlanSinceRequest
	6,  // 12: chash.v1.CHashService.PushBatch:output_type -> chash.v1.PushBatchResponse
	8,  // 13: chash.v1.CHashService.PullRange:output_type -> chash.v1.PullRangeResponse
	10, // 14: chash.v1.CHashService.Replicate:output_type -> chash.v1.ReplicateResponse
	12, // 15: chash.v1.CHashService.AnnouncePlan:output_type -> chash.v1.AckPlan
	14, // 16: chash.v1.CHashService.PullPlanSince:output_type -> chash.v1.PullPlanSinceResponse
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_internal_chash_c_proto_init() }
func file_internal_chash_c_proto_init() {
	if File_internal_chash_c_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_chash_c_proto_rawDesc), len(file_internal_chash_c_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_chash_c_proto_goTypes,
		DependencyIndexes: file_internal_chash_c_proto_depIdxs,
		EnumInfos:         file_internal_chash_c_proto_enumTypes,
		MessageInfos:      file_internal_chash_c_proto_msgTypes,
	}.Build()
	File_internal_chash_c_proto = out.File
	file_internal_chash_c_proto_goTypes = nil
	file_internal_chash_c_proto_depIdxs = nil
}
