// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: internal/chash/c.proto

package chash_grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CHashService_PushBatch_FullMethodName = "/chash.v1.CHashService/PushBatch"
	CHashService_PullRange_FullMethodName = "/chash.v1.CHashService/PullRange"
	CHashService_Replicate_FullMethodName = "/chash.v1.CHashService/Replicate"
)

// CHashServiceClient is the client API for CHashService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CHashServiceClient interface {
	PushBatch(ctx context.Context, in *PushBatchRequest, opts ...grpc.CallOption) (*PushBatchResponse, error)
	PullRange(ctx context.Context, in *PullRangeRequest, opts ...grpc.CallOption) (*PullRangeResponse, error)
	Replicate(ctx context.Context, in *ReplicateRequest, opts ...grpc.CallOption) (*ReplicateResponse, error)
}

type cHashServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCHashServiceClient(cc grpc.ClientConnInterface) CHashServiceClient {
	return &cHashServiceClient{cc}
}

func (c *cHashServiceClient) PushBatch(ctx context.Context, in *PushBatchRequest, opts ...grpc.CallOption) (*PushBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PushBatchResponse)
	err := c.cc.Invoke(ctx, CHashService_PushBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cHashServiceClient) PullRange(ctx context.Context, in *PullRangeRequest, opts ...grpc.CallOption) (*PullRangeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PullRangeResponse)
	err := c.cc.Invoke(ctx, CHashService_PullRange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cHashServiceClient) Replicate(ctx context.Context, in *ReplicateRequest, opts ...grpc.CallOption) (*ReplicateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReplicateResponse)
	err := c.cc.Invoke(ctx, CHashService_Replicate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CHashServiceServer is the server API for CHashService service.
// All implementations must embed UnimplementedCHashServiceServer
// for forward compatibility.
type CHashServiceServer interface {
	PushBatch(context.Context, *PushBatchRequest) (*PushBatchResponse, error)
	PullRange(context.Context, *PullRangeRequest) (*PullRangeResponse, error)
	Replicate(context.Context, *ReplicateRequest) (*ReplicateResponse, error)
	mustEmbedUnimplementedCHashServiceServer()
}

// UnimplementedCHashServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCHashServiceServer struct{}

func (UnimplementedCHashServiceServer) PushBatch(context.Context, *PushBatchRequest) (*PushBatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PushBatch not implemented")
}
func (UnimplementedCHashServiceServer) PullRange(context.Context, *PullRangeRequest) (*PullRangeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PullRange not implemented")
}
func (UnimplementedCHashServiceServer) Replicate(context.Context, *ReplicateRequest) (*ReplicateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Replicate not implemented")
}
func (UnimplementedCHashServiceServer) mustEmbedUnimplementedCHashServiceServer() {}
func (UnimplementedCHashServiceServer) testEmbeddedByValue()                      {}

// UnsafeCHashServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CHashServiceServer will
// result in compilation errors.
type UnsafeCHashServiceServer interface {
	mustEmbedUnimplementedCHashServiceServer()
}

func RegisterCHashServiceServer(s grpc.ServiceRegistrar, srv CHashServiceServer) {
	// If the following call panics, it indicates UnimplementedCHashServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CHashService_ServiceDesc, srv)
}

func _CHashService_PushBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CHashServiceServer).PushBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CHashService_PushBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CHashServiceServer).PushBatch(ctx, req.(*PushBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CHashService_PullRange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PullRangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CHashServiceServer).PullRange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CHashService_PullRange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CHashServiceServer).PullRange(ctx, req.(*PullRangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CHashService_Replicate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplicateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CHashServiceServer).Replicate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CHashService_Replicate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CHashServiceServer).Replicate(ctx, req.(*ReplicateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CHashService_ServiceDesc is the grpc.ServiceDesc for CHashService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CHashService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chash.v1.CHashService",
	HandlerType: (*CHashServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PushBatch",
			Handler:    _CHashService_PushBatch_Handler,
		},
		{
			MethodName: "PullRange",
			Handler:    _CHashService_PullRange_Handler,
		},
		{
			MethodName: "Replicate",
			Handler:    _CHashService_Replicate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/chash/c.proto",
}
