syntax = "proto3";

package chash.v1;

option go_package = "./internal/chash/chash_grpc;chash_grpc";

message KVPair {
    string key = 1;
    string value = 2;
}

message PushBatchRequest {
    repeated KVPair kvs = 1;
}

message PushBatchResponse {
    bool ok = 1;
}

message PullRangeRequest {
    string start_key = 1;
    string end_key = 2;
}

message PullRangeResponse {
    repeated KVPair kvs = 1;
}

message ReplicateRequest {
    repeated KVPair kvs = 1;
}

message ReplicateResponse {
    bool ok = 1;
}

service CHashService {
    rpc PushBatch(PushBatchRequest) returns (PushBatchResponse);
    rpc PullRange(PullRangeRequest) returns (PullRangeResponse);
    rpc Replicate(ReplicateRequest) returns (ReplicateResponse);
}
